version: "3"

services:
  app:
    build: .
    environment:
      - ENVIRONMENT=develop
      - SECRET_KEY=abc123
      - DJANGO_SETTINGS_MODULE=config.dev
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@tna.dev
    env_file: .env
    ports:
      - 65533:8080
    command: sh /home/root/run-dev.sh
    user: root:root
    depends_on:
      - db
    volumes:
      - ./:/app:rw
      - ./run-dev.sh:/home/root/run-dev.sh:r
      - media:/media:rw

  db:
    image: postgres:12.0
    volumes:
      - pgdata:/var/lib/postgresql/data

  dev:
    image: ghcr.io/nationalarchives/tna-python-dev:latest
    volumes:
      - ./:/app

volumes:
  media:
  pgdata:
