# Generated by Django 5.0.1 on 2024-01-23 12:32

import django.db.models.deletion
import wagtail_headless_preview.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("images", "__first__"),
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
    ]

    operations = [
        migrations.CreateModel(
            name="BasePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A short, enticing description of this page.",
                        max_length=160,
                        null=True,
                    ),
                ),
                ("published_date", models.DateField(blank=True, null=True)),
                ("base_og_title", models.TextField(blank=True, max_length=160)),
                (
                    "base_og_description",
                    models.TextField(blank=True, max_length=160),
                ),
                (
                    "facebook_og_title",
                    models.TextField(blank=True, max_length=160),
                ),
                (
                    "facebook_og_description",
                    models.TextField(blank=True, max_length=160),
                ),
                (
                    "twitter_og_title",
                    models.TextField(blank=True, max_length=160),
                ),
                (
                    "twitter_og_description",
                    models.TextField(blank=True, max_length=160),
                ),
                (
                    "twitter_og_author",
                    models.TextField(blank=True, max_length=160),
                ),
                (
                    "base_og_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.baseimage",
                    ),
                ),
                (
                    "facebook_og_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.baseimage",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image that will appear on thumbnails and promos around the site.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.baseimage",
                    ),
                ),
                (
                    "twitter_og_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.baseimage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                wagtail_headless_preview.models.HeadlessPreviewMixin,
                "wagtailcore.page",
            ),
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.basepage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.basepage",),
        ),
    ]
