# Generated by Django 5.0.1 on 2024-01-23 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_exploreindexpage_indexpage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExploreIndex",
        ),
    ]
